#!/bin/bash

if [ ! -s "$0" ]; then
  echo "Error: Script is empty or missing."
  exit 1
fi

if [ ! -f data.json ]; then
  echo "Error: data.json not found."
  exit 1
fi

name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
formatted_height=$(jq -r '.height' data.json | awk '{printf "%.1f", $1 / 10}')
formatted_weight=$(jq -r '.weight' data.json | awk '{printf "%.0f", $1 / 10}')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
